# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UaICLDaG0xxVGa4V1qK0BBC8ra36HAqg
"""

import numpy as np
# Правила транслирования
# 1. Сравниваются размерности двух массивов.Если разномерности отличаются, то форма массива с меньшей размерносьтю дополняется единицами с левой стороны.
# 2. Если формы двух массивов не совпадают в каком-то измерении, то массив с формой, равной 1 в данном измерении, "растягивается" до соотвествия форме другого мссива
# 3. Если в каком-либо измерении размеры массивов различаются и ни один не равен 1, то генерируется ошибка
a = np.ones((2,3))
b = np.arange(3)

print(a)
print(b)

print(a.shape)
print(b.shape)

c = a + b
print(c)
print(c.shape)

# 1. a = (2,3) -> 2, b = (3,) -> 1 => a (2, 3)
# 2. a = (2,3), b = (1,3) -> 1 => b (2, 3)
# 3. a = (2,3), b = (2,3)
# 111
# 111

# 012
# 012

# примеры посложнее
a = np.arange(3).reshape((3,1))
b = np.arange(3)
print(a)
print(b)
print(a.shape)
print(b.shape)

print(a + b)
print(a * b)

a = np.ones((3,2))
b = np.arange(3)
print(a)
print(b)
print(a.shape)
print(b.shape)

# Выдаст ошибку
c = a + b

# Центрирование массивов
a = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
print(a)

aMean = a.mean(0)
print(aMean)

print(a.shape)
print(aMean.shape)

aCentr = a - aMean
print(aCentr)

print(aCentr.mean(0))

a = np.array([[1,2,3,4,5,6,7,8,9], [9,8,7,6,5,4,3,2,1]])
print(a)

aMean = a.mean(1)
print(aMean)

print(a.shape)
print(aMean.shape)

# Добавим вторую ось принудительно
aMean = aMean[:,np.newaxis]
print(aMean)
print(aMean.shape)

aCentr = a - aMean
print(aCentr)
print(aCentr.mean(1))

import matplotlib.pyplot as plt

x = np.linspace(0, 10, 100)
y = np.linspace(0, 10, 100)
y = y[:, np.newaxis]

print(x.shape)
print(x.shape)

z = np.sin(x)*y
plt.colorbar()
plt.imshow()
plt.show()

# Маскирование

x = np.arange(1,6)
print(x)

print(x < 3)
# то же самое
print(np.less(x,3))

print(x > 3)

rng = np.random.default_rng(seed=1)
x = rng.integers(10, size=(3,4))

print(x)
print(x < 6)

# Сколько элементов имеют значение меньше 6
print(np.count_nonzero(x < 6))
print(np.sum(x < 6))

print(np.sum(x < 6, axis=0))
print(np.sum(x < 6, axis=1))

print(np.any(x > 8))
print(np.any(x < 0))

print(np.all(x < 10))
print(np.all(x != 5))

print(np.sum((x > 3) & (x < 9), axis=0))
print(np.sum(np.greater((x, 3)) & (np.less(x, 9)), axis=0))

# Наложение маски
print( x < 5)
a = x[x < 5]
print(a)
print(a.shape)

# and or
print(bool(42), bool(0))
print(bool(42 and 0))
print(bool(42 or 0))

print(bin(42))
print(bin(59))

print(bin(42 and 59))
print(bin(42 or 59))

a = np.array([1, 0, 1, 0,1, 0], dtype=bool)
b = np.array([1,1,1,1,0], dtype = bool)
print(a and b)

# Способы доступа к элементам массива
a = np.arrange(10)

print(a)
print(a[3])
print(a[3:4])
print(a[a==3])

# векторизованная / прихотливая (fancy) индексация
a = np.arrange(1,10)
print(a)
ind = [3,5,0]
print(a[ind])

ind = [[3,5],[0,3]]
print(a[ind])

a = np.arrange(12).reshape((3,4))
print(a)

row = np.array([0, 1, 2])
col = np.array([2, 1, 3])
print(a[row, col])

print(row.shape)
print(col.shape)

print(a[row[:, np.newaxis], col])